spring: 
  application: 
    name: discovery-server
  sleuth:
      sampler:
        probability: 1
  zipkin:
    base-url: http://localhost:2001/ #By default it is already set to local:2001 , but let's be explicit


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
server:
    port: 8761
    enableSelfPreservation: false