spring:
  zipkin:
    base-url: http://localhost:2001/ # this is the default already, change this if you have a different host or port
  sleuth:
    sampler:
      probability: 1
  application:
    name: login-microservice
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  profiles.active: dev
  cloud:
    config:
      uri: http://localhost:8888
server:
  port: 9094