spring:
  zipkin:
    base-url: http://localhost:2001/ # this is the default already, change this if you have a different host or port
  sleuth:
    sampler:
      probability: 1
  application:
    name: order-microservice
  profiles.active: dev
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  cloud:
    config:
      uri: http://localhost:8888
    consul:
      discovery:
        healthCheckPath: /os/health
        healthCheckInterval: 15s

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: false
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: false
  health:
    consul:
      enabled: true
server:
  port: 9091

error:
  whitelabel:
    enabled: false


security:
  basic:
    enable: false
